Repository OpenBioSim/sire, pull requests merged in 2025-01, with the labels that each got.

#273 Add support for replica exchange and REST2
  corelib/src/libs/SireIO/sdf.cpp
  corelib/src/libs/SireMM/CMakeLists.txt
  corelib/src/libs/SireMM/anglerestraint.cpp
  corelib/src/libs/SireMM/anglerestraint.h
  corelib/src/libs/SireMM/anglerestraints.cpp
  corelib/src/libs/SireMM/anglerestraints.h
  corelib/src/libs/SireMM/dihedralrestraint.cpp
  corelib/src/libs/SireMM/dihedralrestraint.h
  corelib/src/libs/SireMM/dihedralrestraints.cpp
  corelib/src/libs/SireMM/dihedralrestraints.h
  corelib/src/libs/SireMol/stereochemistry.cpp
  corelib/src/libs/SireMol/stereochemistry.h
  corelib/src/libs/SireSystem/system.cpp
  doc/source/changelog.rst
  doc/source/contributors.rst
  doc/source/tutorial/part06/02_alchemical_dynamics.rst
  doc/source/tutorial/part06/03_restraints.rst
  doc/source/tutorial/part06/images/06_02_01.jpg
  doc/source/tutorial/part06/images/06_02_02.jpg
  doc/source/tutorial/part06/images/06_02_03.jpg
  doc/source/tutorial/part06/images/06_02_04.jpg
  src/sire/mm/__init__.py
  src/sire/mol/__init__.py
  src/sire/mol/_dynamics.py
  src/sire/mol/_minimisation.py
  src/sire/morph/_perturbation.py
  src/sire/qm/_emle.py
  src/sire/restraints/__init__.py
  src/sire/restraints/_restraints.py
  src/sire/system/_system.py
  tests/convert/test_openmm_constraints.py
  tests/convert/test_openmm_rest2.py
  tests/io/test_sdf.py
  tests/mol/test_dynamics.py
  tests/restraints/test_angle_dihedral_restraints.py
  wrapper/Convert/SireOpenMM/LambdaLever.pypp.cpp
  wrapper/Convert/SireOpenMM/PerturbableOpenMMMolecule.pypp.cpp
  wrapper/Convert/SireOpenMM/_sommcontext.py
  wrapper/Convert/SireOpenMM/lambdalever.cpp
  wrapper/Convert/SireOpenMM/lambdalever.h
  wrapper/Convert/SireOpenMM/openmmminimise.cpp
  wrapper/Convert/SireOpenMM/openmmmolecule.cpp
  wrapper/Convert/SireOpenMM/openmmmolecule.h
  wrapper/Convert/SireOpenMM/sire_to_openmm_system.cpp
  wrapper/MM/AngleRestraint.pypp.cpp
  wrapper/MM/AngleRestraints.pypp.cpp
  wrapper/MM/AngleRestraints.pypp.hpp
  wrapper/MM/CMakeAutogenFile.txt
  wrapper/MM/DihedralRestraint.pypp.cpp
  wrapper/MM/DihedralRestraints.pypp.cpp
  wrapper/MM/DihedralRestraints.pypp.hpp
  wrapper/MM/SireMM_registrars.cpp
  wrapper/MM/_MM.main.cpp
  wrapper/MM/active_headers.h
Labels: bug, enhancement

#272 Feature Angle and Dihedral Restraints
  corelib/src/libs/SireMM/CMakeLists.txt
  corelib/src/libs/SireMM/anglerestraint.cpp
  corelib/src/libs/SireMM/anglerestraint.h
  corelib/src/libs/SireMM/anglerestraints.cpp
  corelib/src/libs/SireMM/anglerestraints.h
  corelib/src/libs/SireMM/dihedralrestraint.cpp
  corelib/src/libs/SireMM/dihedralrestraint.h
  corelib/src/libs/SireMM/dihedralrestraints.cpp
  corelib/src/libs/SireMM/dihedralrestraints.h
  doc/source/changelog.rst
  doc/source/contributors.rst
  doc/source/tutorial/part06/03_restraints.rst
  src/sire/mm/__init__.py
  src/sire/restraints/__init__.py
  src/sire/restraints/_restraints.py
  tests/restraints/test_angle_dihedral_restraints.py
  wrapper/Convert/SireOpenMM/LambdaLever.pypp.cpp
  wrapper/Convert/SireOpenMM/lambdalever.cpp
  wrapper/Convert/SireOpenMM/sire_to_openmm_system.cpp
  wrapper/MM/AngleRestraint.pypp.cpp
  wrapper/MM/AngleRestraints.pypp.cpp
  wrapper/MM/AngleRestraints.pypp.hpp
  wrapper/MM/CMakeAutogenFile.txt
  wrapper/MM/DihedralRestraint.pypp.cpp
  wrapper/MM/DihedralRestraints.pypp.cpp
  wrapper/MM/DihedralRestraints.pypp.hpp
  wrapper/MM/SireMM_registrars.cpp
  wrapper/MM/_MM.main.cpp
  wrapper/MM/active_headers.h
Labels: enhancement

#275 Update to the Alchemical Dynamics docs
  doc/source/tutorial/part06/02_alchemical_dynamics.rst
  doc/source/tutorial/part06/images/06_02_01.jpg
  doc/source/tutorial/part06/images/06_02_02.jpg
  doc/source/tutorial/part06/images/06_02_03.jpg
  doc/source/tutorial/part06/images/06_02_04.jpg
Labels: bug, documentation
